# Generated by Django 2.0.5 on 2018-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Alias',
                'verbose_name_plural': 'Aliass',
            },
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('name',)},
        ),
    ]
