# Generated by Django 2.0.5 on 2018-05-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('aliases', models.ManyToManyField(related_name='aliases', to='person.Alias')),
                ('movies_as_actor', models.ManyToManyField(related_name='movies_as_actor', to='movie.Movie')),
                ('movies_as_director', models.ManyToManyField(related_name='movies_as_director', to='movie.Movie')),
                ('movies_as_producer', models.ManyToManyField(related_name='movies_as_producer', to='movie.Movie')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
