# Generated by Django 2.0.5 on 2018-05-19 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20180518_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alias',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
