# Generated by Django 2.0.5 on 2018-05-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        ('person', '0002_auto_20180518_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(related_name='casting', to='person.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='directors', to='person.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(related_name='producers', to='person.Person'),
        ),
    ]
